AWSTemplateFormatVersion: "2010-09-09"

Description: "Dynamo DB template - Different options: ttl, streams, provisioning..."

Parameters:
  Environment:
    Type: String
    Description: dev/qa/pro 
  TableWCU:
    Type: Number
    Description: Write capacity units of Table
  TableRCU:
    Type: Number
    Description: read capacity units of Table


Conditions:
  IsPro: !Equals 
    - !Ref Environment
    - pro

Resources:
  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "my-table-name"
      GlobalSecondaryIndexes:
      - IndexName: key2-TableIndex
        KeySchema:
        - AttributeName: key2
          KeyType: HASH
        Projection:
          ProjectionType: KEYS_ONLY
      # Enable dynamodb streams
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      # Different data types:
      # https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.DataTypes.html  
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "key2"
          AttributeType: "N"          
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: !If [IsPro, "PROVISIONED", "PAY_PER_REQUEST"]
      ProvisionedThroughput:
        !If
          - IsPro
          - 
            ReadCapacityUnits: !Ref TableRCU
            WriteCapacityUnits: !Ref TableWCU
          - !Ref "AWS::NoValue"
        
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      # Enable SSE to can use KMS
      SSESpecification:
        SSEEnabled: true

Outputs:
  DynamoDBTable:
    Value: !Ref MyTable
    Description: DynamoDB table
  DynamoTableArn:
    Description: ARN Dynamo Table
    Value: !GetAtt MyTable.Arn
  DynamoTableStreamArn:
    Description: ARN Dynamo Table Stream
    Value: !GetAtt MyTable.StreamArn
