AWSTemplateFormatVersion: "2010-09-09"
Description: "Template with some examples of cloudwatch events"

Parameters:
  Resource2TriggerArn:
    Type: String
    Description: Arn of resource that will be triggered by the cloudwatch event.
  Resource2TriggerName:
    Type: String
    Description: Name of resource that will be triggered by the cloudwatch event.

Resources:

    # Event with schedule expression and payload.
    # Target can be a lambda or Step functions, for example
    CWEvent:
      Type: AWS::Events::Rule
      Properties:
        Name: "My Awesome Event Name"
        Description: "My Awesome Event Description"
        # GMT time, all SUNDAYS at 10:00 GMT
        ScheduleExpression: "cron(0 10 ? * SUN *)"
        State: "ENABLED"
        Targets:
          - Arn: !Ref Resource2TriggerArn
            Id: !Ref Resource2TriggerName
            Input: '{"PayloadJsonKey":"PayloadJsonValue"}'