AWSTemplateFormatVersion: "2010-09-09"
Description: Cognito User Pool, Application and User with aad as IDP

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "User Pool"
        Parameters:
          - pUserPoolName
      - Label:
          default: "App Client"
        Parameters:
          - pClientName
      - Label:
          default: "Domain"
        Parameters:
          - pCognitoDomainName
          - pCognitoProviderMetadata
      - Label:
          default: "Callback"
        Parameters:
          - pCallbackUrl

  ParameterLabels:
    pUserPoolName:
      default: "User Pool Name"
    pClientName:
      default: "App Client Name"
    pCognitoDomainName:
      default: "Cognito Domain Name"
    pCognitoProviderMetadata:
      default: "Url for Identity Provider Metadata. Format: https://login.microsoftonline.com/<Directory ID>/federationmetadata/2007-06/federationmetadata.xml?appid=<Application ID>"
    pCallbackUrl:
      default: "Callback after sign-on"

Parameters:
  pUserPoolName:
    Description: "User Pool Name"
    Type: String
  pClientName:
    Description: App name
    Type: String
  pCognitoDomainName:
    Description: Cognito domain name (only the custom part)
    Type: String
  pCognitoProviderMetadata:
    Description: Url for IdP Metadata
    Type: String
  pCallbackUrl:
    Description: Url to redirect after login
    Type: String

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AutoVerifiedAttributes:
        - email
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: false
        DeviceOnlyRememberedOnUserPrompt: false
      EmailVerificationMessage: "Your username is {####} and temporary password is {####}"
      EmailVerificationSubject: "Your temporary password"
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: false
      UsernameAttributes:
        - email
      UserPoolName: !Ref pUserPoolName

  CognitoAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Ref pClientName
      GenerateSecret: true
      RefreshTokenValidity: 7
      UserPoolId: !Ref CognitoUserPool
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - !Ref pCallbackUrl
        - !Join ["", [!Ref pCallbackUrl, "/"]]
        - !Join ["/", [!Ref pCallbackUrl, "parseauth"]]  
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
       - !Ref CognitoIdentityProvider
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref pCognitoDomainName
      UserPoolId: !Ref CognitoUserPool

  CognitoIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      ProviderDetails:
        MetadataURL: !Ref pCognitoProviderMetadata
      AttributeMapping:
        email: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
      ProviderName: "AAD"
      ProviderType: "SAML"
      UserPoolId: !Ref CognitoUserPool

Outputs:
  UserPoolArn:
    Description: "User Pool Arn"
    Value: !GetAtt CognitoUserPool.Arn
  UserPoolClientId:
    Description: "App Client Id"
    Value: !Ref CognitoAppClient
  UserPoolDomain:
    Description: "Domain"
    Value: !Ref pCognitoDomainName
  LoginUrl:
    Description: "Login URL Only with SAML (Ireland Region)"
    Value:  
        - !Join
          - ""
          - - https://
            - !Ref pCognitoDomainName
            - ".auth.eu-west-1.amazoncognito.com/oauth2/authorize?identity_provider=aad&redirect_uri={redirect}&response_type=TOKEN&client_id="
            - !Ref CognitoAppClient
            - "&scope=email openid" 
  LoginUrlDevTest:
    Description: "Login URL Only with SAML and UserPool (Ireland Region)"
    Value:
      - !Join
        - ""
        - - https://
          - !Ref pCognitoDomainName
          - ".auth.eu-west-1.amazoncognito.com/login?response_type=token&client_id="
          - !Ref CognitoAppClient
          - "&redirect_uri={redirect}" 