AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to deploy cognito user pool with aad as IDP"
Parameters:
  env:
    Type: String
    Description: Environment
    Default: ""
  pCallbackUrl:
    Type: String
    Description: CNAME, cloudfront DNS or ALB DNS url
  providerMetadataUrl:
    Type: String
    Description: "Url for Identity Provider Metadata. Format: https://login.microsoftonline.com/<Directory ID>/federationmetadata/2007-06/federationmetadata.xml?appid=<Application ID>"
  pUserPoolName:
    Description: "User Pool Name"
    Type: String  
  pClientName:
    Description: App name
    Type: String      
  pOicdClientId:
    Type: String    
  pOicdSecret:
    Type: String
  pOicdTenantId:
    Type: String
  pCognitoDomainName:
    Type: String  

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AutoVerifiedAttributes:
        - email
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: false
        DeviceOnlyRememberedOnUserPrompt: false
      EmailVerificationMessage: "Your username is {####} and temporary password is {####}"
      EmailVerificationSubject: "Your temporary password"
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      UsernameAttributes:
        - email
      UserPoolName: !Ref pUserPoolName

  CognitoAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Ref pClientName
      GenerateSecret: true
      RefreshTokenValidity: 7
      UserPoolId: !Ref CognitoUserPool
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - !Ref pCallbackUrl
        - !Join ["", [!Ref pCallbackUrl, "/"]]
        - !Join ["/", [!Ref pCallbackUrl, "parseauth"]]        
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - [!Ref UserPoolIdentityProviderOIDC]
        # For dev/test purposes - [!Ref UserPoolIdentityProviderOIDC, "COGNITO"]
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH

  UserPoolIdentityProviderOIDC:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ProviderName: "OIDC"
      ProviderDetails:
        client_id: !Ref pOicdClientId
        client_secret: !Ref pOicdSecret
        attributes_request_method: "GET"
        oidc_issuer: !Join ["", ["https://login.microsoftonline.com/", !Ref pOicdTenantId, "/v2.0"]]
        authorize_scopes: "email profile openid"
      ProviderType: "OIDC"
      AttributeMapping:
        email: "email"

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Domain: !Ref pCognitoDomainName
    DependsOn: CognitoUserPool

Outputs:
  CognitoUserPool:
    Value: !Ref CognitoUserPool
  CognitoAppClient:
    Value: !Ref CognitoAppClient
  CognitoUserPoolArn:
    Value: !GetAtt CognitoUserPool.Arn
  LoginUrl:
    Description: URL of your API endpoint (Ireland Region)
    Value: 
      - !Join
        - ""
        - - https://
          - !Ref pCognitoDomainName
          - ".auth.eu-west-1.amazoncognito.com/oauth2/authorize?identity_provider=oidc&redirect_uri={redirect}&response_type=TOKEN&client_id="
          - !Ref CognitoAppClient
          - "&scope=email openid"
  LoginUrDevTest:
    Description: URL of your API endpoint (Ireland Region)
    Value:                   
      - !Join
        - ""
        - - https://
          - !Ref pCognitoDomainName
          - ".auth.eu-west-1.amazoncognito.com/login?response_type=token&client_id="
          - !Ref CognitoAppClient
          - "&redirect_uri={redirect}"
