AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create S3 private bucket that trigger a lambda on put Object

Parameters:
  LambdaArn:
    Type: String
    Description: lambda Arn

Resources:

  #######################################################################################
  # Bucket CF error unable to validate the following destination configurations         #
  # To avoid this problem, Remove NotificationConfiguration section from S3,            #
  # create bucket and permission and then, update stack with NotificationConfiguration  #
  # section.                                                                            #
  #######################################################################################
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: True
          BlockPublicPolicy: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True
        BucketName: "my-awesome-bucket-name"
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: "s3:ObjectCreated:*"
              Function: !Ref LambdaArn

  # Section to invoke lambda after upload file to S3
  LambdaInvokePermission:
      Type: "AWS::Lambda::Permission"
      DependsOn:
        - S3Bucket
      Properties:
        FunctionName: !Ref LambdaArn
        Action: "lambda:InvokeFunction"
        Principal: s3.amazonaws.com
        SourceAccount: !Ref 'AWS::AccountId'
        SourceArn: !GetAtt S3Bucket.Arn

Outputs:
  BucketArn:
    Value: !GetAtt S3Bucket.Arn
    Description: Arn of bucket
