AWSTemplateFormatVersion: "2010-09-09"
Description: "Basic Lambda template. Create an Cloudwatch log goup and alarm errors"
Transform: AWS::Serverless-2016-10-31

Parameters:
  RoleArn:
    Type: String
    Description: Arn of lambda role
  Name:
    Type: String
    Description: Lambda name
  AlarmSNSTopicARN:
    Type: String
    Description: SNS topic Arn

  LambdaFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Ref Name
      CodeUri: ../src # relative path from template to src folfer
      Handler: main.lambda_handler # path to main function
      Runtime: python3.7 # Your language. See avaliable
      Timeout: 900
      Role: !Ref RoleArn      

  FunctionGetLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: LambdaFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaFunction}
      RetentionInDays: 30

   # Any error on Lambda throws an error
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: lambda-alarm-name
      AlarmDescription: >
        {
          "Description": "",
          "Procedure": """,
          "Documentation:" "",
          "Contact": ""
        }
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
      - Name: FunctionName
        Value:
          Ref: LambdaFunction
      Period: 60
      EvaluationPeriods: 1
      Statistic: Sum
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      ActionsEnabled: True
      AlarmActions:
        - !Ref AlarmSNSTopicARN       