AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to deploy one secrets manager with multiple parameters in a JSON format"

Parameters:
  SecretName:
    Type: String
    Description: Secret Name
  # Distinct values to inser... Depends of your interests  
  pValue1:
    Type: String
  pValue2:
    Type: String
  pValue3:
    Type: String

Resources:
  MySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      Description: My super secret JSON
      SecretString:
        Fn::Join:
          - ""
          - - "{"
            - "\"value1Name\":\""
            - !Ref pValue1
            - "\", \"value2Name\":\""
            - !Ref pValue2
            - "\", \"value3Name\":\""
            - !Ref pValue3
            - "\"}"

  MySecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref MySecret
      ResourcePolicy:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
             - secretsmanager.amazonaws.com
          # Fine grained here from your security requirements...
          Action:
          - "secretsmanager:*"
          Resource: "*"
Outputs:
  SecretName:
    Description: Secret Name
    Value: !Ref SecretName
